import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to anon,authenticated,service_role;`);
const sql=readFileSync('supabase/migrations/202609060001_brief_community.sql','utf8');
await db.exec(sql);await db.exec(sql);
const cultureSQL=readFileSync('supabase/migrations/202609060002_brief_culture.sql','utf8');await db.exec(cultureSQL);await db.exec(cultureSQL);
const u1='11111111-1111-4111-8111-111111111111',u2='22222222-2222-4222-8222-222222222222',u3='33333333-3333-4333-8333-333333333333';
const k1='event:aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',k2='paper:abcdef0123456789abcdef01';
await db.query(`insert into auth.users values($1,'first@example.test',now()),($2,'second@example.test',now()),($3,'unverified@example.test',null)`,[u1,u2,u3]);
await db.query(`insert into public.brief_community_items(story_key,headline,url,kind,published_date) values($1,'First story','https://example.test/story/first/','news',current_date),($2,'Research paper','https://example.test/research/second/','research',current_date)`,[k1,k2]);
async function role(r,u=''){await db.exec('reset role');await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[u]);await db.exec('set role '+r);}
let checks=0;
async function blocked(sql,args=[]){await assert.rejects(()=>db.query(sql,args));checks++;}
await role('anon');await blocked('select * from public.brief_community_profiles');await blocked('select public.brief_community_toggle($1,\'like\',true)',[k1]);
await role('authenticated',u3);await blocked('select public.brief_community_toggle($1,\'like\',true)',[k1]);
await role('authenticated',u1);
for(let i=0;i<2;i++)await db.query(`select public.brief_community_toggle($1,'like',true)`,[k1]);
let r=await db.query('select public.brief_community_metrics($1) as m',[[k1]]);assert.equal(r.rows[0].m[k1].likes,1);assert.equal(r.rows[0].m[k1].liked,true);checks++;
await db.query(`select public.brief_community_toggle($1,'save',true)`,[k2]);
r=await db.query(`select public.brief_community_comment($1,'First reader','A useful question about the findings.',null) as id`,[k1]);const comment=r.rows[0].id;
await role('anon');r=await db.query('select public.brief_community_comments_for($1) as comments',[k1]);assert.equal(r.rows[0].comments.length,0);checks++;
await role('authenticated',u2);await blocked('select public.brief_community_moderation_queue()');r=await db.query('select public.brief_community_delete_comment($1) as deleted',[comment]);assert.equal(r.rows[0].deleted,false);checks++;
r=await db.query('select public.brief_community_my_data() as d');assert.deepEqual(r.rows[0].d.saves,[]);checks++;
await role('service_role');await db.query('insert into public.brief_community_moderators values($1)',[u2]);
await role('authenticated',u2);await db.query(`select public.brief_community_moderate($1,'published')`,[comment]);
await role('anon');r=await db.query('select public.brief_community_comments_for($1) as comments',[k1]);assert.equal(r.rows[0].comments.length,1);assert.equal('user_id' in r.rows[0].comments[0],false);checks++;
await role('authenticated',u1);await blocked(`select public.brief_community_comment($1,'Reader','Reply sent to the wrong story.', $2)`,[k2,comment]);
await role('anon');await db.query('select public.brief_community_record_read($1,$2,20,.5)',[k1,u1]);await db.query('select public.brief_community_record_read($1,$2,20,.5)',[k1,u1]);
r=await db.query('select public.brief_community_metrics($1) as m',[[k1]]);assert.equal(r.rows[0].m[k1].reads,1);assert.equal(r.rows[0].m[k1].liked,false);checks++;
r=await db.query('select public.brief_community_record_read($1,$2,10,.8) as r',[k1,u2]);assert.equal(r.rows[0].r,false);checks++;
await blocked('select public.brief_community_maintain()');await blocked('select * from public.brief_sponsor_enquiries');await blocked('select * from public.brief_editorial_provenance');
await role('authenticated',u1);await blocked(`select public.brief_community_sponsor('Reader','second@example.test','Company','Please tell me about sponsorship.')`);
await db.query(`select public.brief_community_sponsor('Reader','first@example.test','Company','Please tell me about sponsorship.')`);
await db.query('select public.brief_community_delete_profile()');r=await db.query('select public.brief_community_my_data() as d');assert.deepEqual(r.rows[0].d.saves,[]);assert.deepEqual(r.rows[0].d.likes,[]);assert.deepEqual(r.rows[0].d.comments,[]);checks++;
await role('service_role');await db.query('insert into public.brief_community_reads values($1,$2,current_date-91,30)',[k2,u2]);r=await db.query('select public.brief_community_maintain() as n');assert.equal(r.rows[0].n,1);checks++;
const cultureKey='culture:1234567890abcdef12345678';await db.query(`insert into public.brief_community_items(story_key,headline,url,kind,published_date) values($1,'Daily poem','https://example.test/culture/daily/','culture',current_date)`,[cultureKey]);await role('authenticated',u2);await db.query(`select public.brief_community_toggle($1,'like',true)`,[cultureKey]);await db.query(`select public.brief_community_toggle($1,'save',true)`,[cultureKey]);await db.query(`select public.brief_community_comment($1,'Second reader','A thoughtful daily selection.',null)`,[cultureKey]);r=await db.query('select public.brief_community_metrics($1) as m',[[cultureKey]]);assert.equal(r.rows[0].m[cultureKey].likes,1);checks++;await role('anon');r=await db.query('select public.brief_community_comments_for($1) as comments',[cultureKey]);assert.equal(r.rows[0].comments.length,0);checks++;
console.log(JSON.stringify({postgres:'PGlite',migration_runs:4,checks_passed:checks}));await db.close();
