'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),crypto=require('node:crypto');
function setup(){
 const config={supabase_url:'https://example.supabase.co',supabase_publishable_key:'sb_publishable_test',layout_version:'test-v1',release_id:'2026-W36'};
 const key='event:11111111-1111-4111-8111-111111111111',calls=[],local=new Map(),session=new Map();let fail=false;
 const storage=m=>({getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)});
 const nodes={'brief-config':{textContent:JSON.stringify(config)},'brief-items':{textContent:JSON.stringify([{key,kind:'news',path:'story/test/index.html',content_hash:'a'.repeat(64)}])},'ux-storage-status':{}};
 const document={getElementById:k=>nodes[k]||null,body:{dataset:{page:'home'}},addEventListener:()=>{},querySelectorAll:()=>[],hidden:false};
 const window={};const context={window,document,crypto:{randomUUID:crypto.randomUUID},localStorage:storage(local),sessionStorage:storage(session),location:{origin:'https://brief.test',href:'https://brief.test/'},innerWidth:1200,innerHeight:800,URL,Date,console,setInterval:()=>{},setTimeout:()=>{},clearTimeout:()=>{},addEventListener:()=>{},fetch:async(url,opts)=>{const body=JSON.parse(opts.body);calls.push({url,body,opts});if(fail){fail=false;throw Error('offline');}return {ok:true,json:async()=>url.endsWith('brief_ux_consent')?{token:body.p_analytics||body.p_research?'b'.repeat(64):null,analytics:body.p_analytics,research:body.p_research}:url.endsWith('brief_ux_record')?body.p_events.length:1};}};
 vm.runInNewContext(fs.readFileSync('assets/ux-history.js','utf8'),context);return {ux:window.BriefUX,calls,local,key,setFail:()=>{fail=true;}};
}
test('No collection before consent and no RPC on initial decline',async()=>{const a=setup();assert.equal(a.ux.track('page_view'),false);await a.ux.start(false,false);assert.equal(a.calls.length,0);});
test('Independent research-only choice stores events, without Google',async()=>{const a=setup();await a.ux.start(false,true);await a.ux.flush();assert.equal(a.calls[0].body.p_analytics,false);assert.equal(a.calls[0].body.p_research,true);assert.equal(a.calls[1].body.p_events[0].name,'page_view');assert.equal(a.calls[1].opts.referrerPolicy,'no-referrer');assert.equal(a.ux.status(),'ready');});
test('Unknown events and unregistered stories rejected; PII discarded',async()=>{const a=setup();await a.ux.start(true,false);assert.equal(a.ux.track('unknown'),false);assert.equal(a.ux.track('like',{story_key:'unknown'}),false);a.ux.track('like',{story_key:a.key,email:'private@test',query:'private search',body:'comment',position:1});await a.ux.flush();const e=a.calls[1].body.p_events[1];assert.equal(e.name,'like');assert.equal(e.properties.position,1);assert.equal(e.properties.email,undefined);assert.equal(e.properties.body,undefined);assert.equal(e.properties.query,undefined);});
test('Retry preserves event IDs for server deduplication',async()=>{const a=setup();await a.ux.start(true,false);a.setFail();await a.ux.flush();const first=a.calls[1].body.p_events[0].id;await a.ux.flush();assert.equal(a.calls[2].body.p_events[0].id,first);});
test('Withdrawal stops new events and revokes with previous token',async()=>{const a=setup();await a.ux.start(true,true);await a.ux.start(false,false);assert.equal(a.calls[1].body.p_token,'b'.repeat(64));assert.equal(a.ux.track('page_view'),false);await a.ux.flush();assert.equal(a.calls.length,2);});
test('Erasure calls database and removes local access',async()=>{const a=setup();await a.ux.start(false,true);await a.ux.erase();assert.ok(a.calls[1].url.endsWith('brief_ux_erase'));assert.equal(a.local.size,0);assert.equal(a.ux.status(),'off');});
test('Failed consent request stays closed to collection',async()=>{const a=setup();a.setFail();await a.ux.start(true,true);assert.equal(a.ux.status(),'error');assert.equal(a.ux.track('page_view'),false);});
